name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: '${{ secrets.CYPRESS_baseUrl }}'
          record: true
        env:
          CYPRESS_baseUrl: ${{ secrets.CYPRESS_baseUrl }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
