name: End-to-end tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm build && npm start
          wait-on: $CYPRESS_baseUrl
        env:
          CYPRESS_baseUrl: ${{ secrets.CYPRESS_baseUrl }}
